CREATE TABLE bank_accounts (
    id BIGINT PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    account_number VARCHAR(255) NOT NULL,
    balance DECIMAL(19,2) NOT NULL,
    document_id VARCHAR(255),
    access_pin_hash VARCHAR(255),
    transaction_pin_hash VARCHAR(255),
    savings_balance DECIMAL(19,2) DEFAULT 0 NOT NULL,
    savings_goal DECIMAL(19,2) DEFAULT 5000 NOT NULL,
    card_limit DECIMAL(19,2) DEFAULT 6000 NOT NULL,
    card_spent DECIMAL(19,2) DEFAULT 1248.90 NOT NULL,
    card_blocked BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE bank_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    detail VARCHAR(255),
    amount DECIMAL(19,2),
    type VARCHAR(255)
);

CREATE TABLE connected_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    type VARCHAR(255),
    location VARCHAR(255),
    last_access VARCHAR(255),
    trusted BOOLEAN DEFAULT FALSE NOT NULL,
    blocked BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE scheduled_operation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    kind VARCHAR(255),
    recipient VARCHAR(255),
    amount DECIMAL(19,2),
    scheduled_date DATE,
    status VARCHAR(255)
);
