ALTER TABLE bank_accounts ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE bank_accounts ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE bank_accounts ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0 NOT NULL;

UPDATE bank_accounts SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;

CREATE UNIQUE INDEX uq_bank_accounts_document ON bank_accounts(document_id);
CREATE UNIQUE INDEX uq_bank_accounts_number ON bank_accounts(account_number);
CREATE UNIQUE INDEX uq_bank_accounts_email ON bank_accounts(email);

CREATE TABLE bank_sessions (
    token_hash VARCHAR(64) PRIMARY KEY,
    account_id BIGINT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_bank_sessions_account ON bank_sessions(account_id);
CREATE INDEX idx_bank_sessions_expiration ON bank_sessions(expires_at);

CREATE TABLE pix_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    key_type VARCHAR(32) NOT NULL,
    normalized_key VARCHAR(255) NOT NULL,
    display_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX uq_pix_keys_normalized ON pix_keys(normalized_key);
CREATE INDEX idx_pix_keys_account ON pix_keys(account_id);
